server:
  port: 8888


# 配置京东参数模板
app:
  key: # 填自己得京东参数
  secret: # 填自己得京东参数
  
  

# 是否开启
open:
  mail: true # 开启邮件通知
  wx: false # 开启微信通知
  filterPaid: true # 是否开启过滤未付款数据



# 配置邮件发送着参数
spring:
  mail:
    port: 465
    default-encoding: UTF-8
    host: smtp.qq.com
    username: # 填自己配置得邮箱
    password: # 填邮箱生成得密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            require: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false



# 配置邮件接收者邮箱
mail:
  receive: # 自己接收邮件的邮箱

# 配置微信发送
wx:
  send:
    url: # 填写微信发送通知ULR




# 配置定时任务执行时间间隔
lyj:
  quartz:
    task: 0 */1 * * * ?  #每 5 分钟